# .github/workflows/release.yml
name: Tag and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch  # or "minor", "major"
